Import('rtconfig')
from building import *

#get current directory
cwd = GetCurrentDir()

# Update include path
path = [ cwd + '/debug_console']

# The set of source files associated with this SConscript file.
src = []

src += ['debug_console/hpm_debug_console.c']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path)

Return ('group')
