Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the startup files

src = ['startup.c']

use_local_interrupt = not GetDepend('HPM_USING_RTTHREAD_INTERRUPT_FRAMEWORK')

if use_local_interrupt:
    src += ['trap.c']

if rtconfig.PLATFORM in ['gcc', 'zcc']:
    src += [os.path.join('toolchains', 'gcc', 'start.S')]
    if use_local_interrupt:
        src += [os.path.join('toolchains', 'gcc', 'port_gcc.S')]
elif rtconfig.PLATFORM in ['segger']:
    src += [os.path.join('toolchains', 'segger', 'start.s')]
    src += [os.path.join('toolchains', 'reset.c')]
    if use_local_interrupt:
        src += [os.path.join('toolchains', 'gcc', 'port_gcc.S')]
CPPPATH = [cwd]
CPPDEFINES=['D45', rtconfig.CHIP_NAME]

group = DefineGroup('Startup', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
