Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the startup files

src = ['trap.c', 'startup.c']

if rtconfig.PLATFORM in ['gcc', 'zcc']:
    src += [os.path.join('toolchains', 'gcc', 'start.S')]
    src += [os.path.join('toolchains', 'gcc', 'port_gcc.S')]
elif rtconfig.PLATFORM in ['segger']:
    src += [os.path.join('toolchains', 'segger', 'start.s')]
    src += [os.path.join('toolchains', 'gcc', 'port_gcc.S')]
    src += [os.path.join('toolchains', 'reset.c')]
CPPPATH = [cwd]
CPPDEFINES=['D45', rtconfig.CHIP_NAME]

group = DefineGroup('Startup', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
