import os
import sys
Import('rtconfig')
from building import *

#get current directory
cwd = GetCurrentDir()

# Update include path
path = [ cwd ]

# The set of source files associated with this SConscript file.
src = Split('''
    hpm_bootheader.c
''')


group = DefineGroup('SoC', src, depend = [''], CPPPATH = path)

Return ('group')
