import os
import rtconfig
from building import *


objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')) and item == rtconfig.SOC_FAMILY:
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
