from building import *

cwd = GetCurrentDir()

# add the general drivers
src = Split("""
    board.c
    pinmux.c
    rw007_port.c
""")

CPPPATH = [cwd]
CPPDEFINES=['D45', 'HPM6750']

group = DefineGroup('Board', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
