/*
 * Copyright (c) 2021-2025 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */
#ifndef HPM_SOC_IP_FEATURE_H
#define HPM_SOC_IP_FEATURE_H

/* GPTMR related feature */
#define HPM_IP_FEATURE_GPTMR_MONITOR 1
#define HPM_IP_FEATURE_GPTMR_OP_MODE 1
#define HPM_IP_FEATURE_GPTMR_CNT_MODE 1
#define HPM_IP_FEATURE_GPTMR_BURST_MODE 1
#define HPM_IP_FEATURE_GPTMR_QEI_MODE 1

/* UART related feature */
#define HPM_IP_FEATURE_UART_RX_IDLE_DETECT 1
#define HPM_IP_FEATURE_UART_FCRR 1
#define HPM_IP_FEATURE_UART_RX_EN 1
#define HPM_IP_FEATURE_UART_E00018_FIX 1
#define HPM_IP_FEATURE_UART_9BIT_MODE 1
#define HPM_IP_FEATURE_UART_ADDR_MATCH 1
#define HPM_IP_FEATURE_UART_TRIG_MODE 1
#define HPM_IP_FEATURE_UART_FINE_FIFO_THRLD 1
#define HPM_IP_FEATURE_UART_IIR2 1
#define HPM_IP_FEATURE_UART_STOP_BIT 1
#define HPM_IP_FEATURE_UART_DISABLE_DMA_TIMEOUT 1
#define HPM_IP_FEATURE_UART_RX_LINE_ERROR_DETECT 1
#define HPM_IP_FEATURE_UART_DMA_STOP 1
#define HPM_IP_FEATURE_UART_BAUD_ACT_ENJ_PLCK 1
#define HPM_IP_FEATURE_UART_DE_DELAY 1

/* I2C related feature */
#define HPM_IP_FEATURE_I2C_SUPPORT_RESET 1

/* SPI related feature */
#define HPM_IP_FEATURE_SPI_NEW_TRANS_COUNT 1
#define HPM_IP_FEATURE_SPI_CS_SELECT 1
#define HPM_IP_FEATURE_SPI_SUPPORT_DIRECTIO 1
#define HPM_IP_FEATURE_SPI_DMA_TX_REQ_AFTER_CMD_FO_MASTER 1
#define HPM_IP_FEATURE_SPI_CS_EDGE_DETECT_FOR_SLAVE 1

/* EWDG related feature */
#define HPM_IP_FEATURE_EWDG_SOC_SUPPORT_TIMEOUT_INTERRUPT 1

/* DMAV2 related feature */
#define HPM_IP_FEATURE_DMAV2_BURST_IN_FIXED_TRANS 1
#define HPM_IP_FEATURE_DMAV2_BYTE_ORDER_SWAP 1

/* PPI related feature */
#define HPM_IP_FEATURE_PPI_DM_POLARITY_EACH_CS 1

/* LOBS related feature */
#define HPM_IP_FEATURE_LOBS_COMP_LOGIC 1
#define HPM_IP_FEATURE_LOBS_IRQ_CTRL 1
#define HPM_IP_FEATURE_LOBS_TRIG_ADDR 1
#define HPM_IP_FEATURE_LOBS_CNT_DATA_NUM 1
#define HPM_IP_FEATURE_LOBS_SAMPLE_RATE_EXT 1

/* ADC16 related feature */
#define HPM_IP_FEATURE_ADC16_HAS_MOT_EN 1
#define HPM_IP_FEATURE_ADC16_HAS_DIFF_MODE 1

/* ACMP related feature */
#define HPM_IP_FEATURE_ACMP_HAS_CAP_SEL 1
#define HPM_IP_FEATURE_ACMP_DAC_MATRIX 1
#define HPM_IP_FEATURE_ACMP_12BIT_DAC 1
#define HPM_IP_FEATURE_ACMP_FILT_LEN_EXTEND 1

/* SDM related feature */
#define HPM_IP_FEATURE_SDM_GATE_FUNC 1
#define HPM_IP_FEATURE_SDM_TIMESTAMP_FUNC 1

/* PLB related feature */
#define HPM_IP_FEATURE_PLB_COUNTER_READ_REAL_TIME 1

/* TRGM related feature */
#define HPM_IP_FEATURE_TRGM_HAS_TRGM_IN_OUT_STATUS 1

/* ENET related feature */
#define HPM_IP_FEATURE_ENET_HAS_MII_MODE 1

/* ESC related feature */
#define HPM_IP_FEATURE_ESC_BYTE_READ 1
#define HPM_IP_FEATURE_ESC_PORT_DIS 1
#define HPM_IP_FEATURE_ESC_SYNC_IRQ_MASK 1
#define HPM_IP_FEATURE_ESC_GPIO_BYTE_CTRL 1

#endif /* HPM_SOC_IP_FEATURE_H */