Import('rtconfig')
from building import *

#get current directory
cwd = GetCurrentDir()

# Update include path
path = [ cwd + '/arch', cwd + "/drivers/inc", cwd + '/soc/ip']

# The set of source files associated with this SConscript file.
src = []

src += ['drivers/src/hpm_pmp_drv.c']
src += ['drivers/src/hpm_pllctl_drv.c']
src += ['drivers/src/hpm_dma_drv.c']


if GetDepend(['BSP_USING_GPIO']):
    src += ['drivers/src/hpm_gpio_drv.c']

if GetDepend(['BSP_USING_UART']):
    src += ['drivers/src/hpm_uart_drv.c']

if GetDepend(['BSP_USING_I2C']):
    src += ['drivers/src/hpm_i2c_drv.c']

if GetDepend(['BSP_USING_SPI']):
    src += ['drivers/src/hpm_spi_drv.c']

if GetDepend(['BSP_USING_RTC']):
    src += ['drivers/src/hpm_rtc_drv.c']

if GetDepend(['BSP_USING_WDT']):
    src += ['drivers/src/hpm_wdog_drv.c']

if GetDepend(['BSP_USING_ADC']):
    src += ['drivers/src/hpm_adc12_drv.c']

if GetDepend(['BSP_USING_CAN']):
    src += ['drivers/src/hpm_can_drv.c']

if GetDepend(['BSP_USING_ETH']):
    src += ['drivers/src/hpm_enet_drv.c']

if GetDepend(['BSP_USING_DMA']):
    src += ['drivers/src/hpm_dma_drv.c']

if GetDepend(['BSP_USING_SDIO']):
    src += ['drivers/src/hpm_sdxc_drv.c']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path)

Return ('group')
