from building import *

cwd = GetCurrentDir()

src = []

if GetDepend('BSP_USING_GPIO'):
    src += ['drv_gpio.c']
    
if GetDepend('BSP_USING_UART'):
    src += [ 'drv_uart.c']

if GetDepend('BSP_USING_SPI'):
    src += [ 'drv_spi.c']

if GetDepend('BSP_USING_RTC'):
    src += ['drv_rtc.c']

if GetDepend('BSP_USING_WDT'):
    src += ['drv_wdt.c']


path = [cwd, cwd + '/config']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
