import rtconfig

from building import *

cwd = GetCurrentDir()

src = Glob('*.c')

CPPDEFINES=[]
CPPPATH = [cwd]
CPPPATH += [ os.path.join(cwd, 'inc') ]
CPPPATH += [ os.path.join(cwd, 'inc', 'jpeg_encode') ]


group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
